
name: PR Tests

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    env:
      PORT: 8080
      NODE_ENV: local
      SECRET: ihaveasecret

    steps:
    - name: Setup Action
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install Node Packages
      run: npm ci
    - name: Run Tests
      run: npm test
